version: "3"
services:   
    api: 
        image: webiste_api
        build: ./api
        ports:
            - "4000:4000"
        links: 
            - mongo:27017
        volumes: 
            - ./api:/app
            - /app/node_modules
        depends_on: 
            - "mongo"
    mongo:
        image: "mongo"
        ports: 
            - "27017:27017" 